packages:
  - services/*
  - domains/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/core': ^1.25.1
  sucrase>glob: 10.5.0

savePrefix: ''

syncInjectedDepsAfterScripts:
  - build
